### ISSUE TITLE
Java Desktop api not supported on Mac and Linux

### ISSUE THREAD

**Issue by james2432** [osmottawa/OSVUploadr#1]
The Desktop.Browse is not implemented in Mac or Linux as Linux maybe running Kde, ldxe, Gnome, etc where as Mac well just doesn't follow the standards. Replace the browse with a system specific command

**Comment by DenisCarriere** [comment]
Still having errors.

```
java -jar target/OSVUploadr-0.1.2.1-ALPHA-jar-with-dependencies.jar
GetOSMUser
Sep 01, 2016 1:47:53 PM ca.osmcanada.osvuploadr.JPMain jButton3ActionPerformed
SEVERE: GetOSMUser
com.github.scribejava.core.exceptions.OAuthException: Response body is incorrect. Can't extract token and secret from this: '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
...
    at com.github.scribejava.core.extractors.AbstractOAuth1TokenExtractor.extract(AbstractOAuth1TokenExtractor.java:39)
    at com.github.scribejava.core.extractors.AbstractOAuth1TokenExtractor.extract(AbstractOAuth1TokenExtractor.java:29)
    at com.github.scribejava.core.extractors.AbstractOAuth1TokenExtractor.extract(AbstractOAuth1TokenExtractor.java:17)
```

**Comment by james2432** [comment]
You need to input an api key and a secret, I didnt upload these to github as I don't want to share the official key

**Comment by DenisCarriere** [comment]
Send me an email how to do that, is that done when you execute the Jar?

**Comment by james2432** [comment]
Line 80&81 of JpMain.java          

 .apiKey("[api key here]")
.apiSecret("[secret here]")

I'll email you the api keys(you seem to be compiling)

**Comment by DenisCarriere** [comment]
Compiling seems to work just fine.

Ok I've got further, the OpenStreetMap browser opened up.
I entered the validation code without the "**.**"

Now I'm getting this error when I submit the upload.

```
$ java -jar OSVUploadr-0.1.2.1-ALPHA-jar-with-dependencies.jar
GetOSMUser
Trying to exec:
   cmd = open
   args = %s
   %s = http://www.openstreetmap.org/oauth/authorize?oauth_token=6WmoBmLBsk4Wv9IYk7Hc3pG2yA895bXG82pZGVqa
Process is running.
Sep 01, 2016 2:09:28 PM ca.osmcanada.osvuploadr.JPMain SendFinished
SEVERE: null
java.io.IOException: Server returned HTTP response code: 400 for URL: http://openstreetview.com/1.0/sequence/finished-uploading/
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
    at ca.osmcanada.osvuploadr.JPMain.SendFinished(JPMain.java:155)
    at ca.osmcanada.osvuploadr.JPMain.Process(JPMain.java:421)
    at ca.osmcanada.osvuploadr.JPMain.jButton3ActionPerformed(JPMain.java:634)
    at ca.osmcanada.osvuploadr.JPMain.access$300(JPMain.java:58)
    at ca.osmcanada.osvuploadr.JPMain$6.actionPerformed(JPMain.java:474)
...
```

**Comment by james2432** [comment]
Is there a sequence_id file in the folder? Also what does your id_file.txt contain?

**Comment by james2432** [comment]
I've added extra logging to the output, could you try again?

**Comment by DenisCarriere** [comment]
It does include an **id_file.txt**

```
472018;DenisCarriere
```

Here's the output right now:

```
$ java -jar target/OSVUploadr-0.1.2.1-ALPHA-jar-with-dependencies.jar 
externalUserId:472018|sequenceId:-1
Sep 01, 2016 6:46:44 PM ca.osmcanada.osvuploadr.JPMain SendFinished
SEVERE: null
java.io.IOException: Server returned HTTP response code: 400 for URL: http://openstreetview.com/1.0/sequence/finished-uploading/
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
    at ca.osmcanada.osvuploadr.JPMain.SendFinished(JPMain.java:156)
    at ca.osmcanada.osvuploadr.JPMain.Process(JPMain.java:423)
    at ca.osmcanada.osvuploadr.JPMain.jButton3ActionPerformed(JPMain.java:636)
    at ca.osmcanada.osvuploadr.JPMain.access$300(JPMain.java:58)
    at ca.osmcanada.osvuploadr.JPMain$6.actionPerformed(JPMain.java:476)
```

**Comment by james2432** [comment]
sequenceId:-1
You aren't getting the sequence from the website for some reason(maybe previous failed upload), can you delete the sequence file in the folder and try again?

**Comment by DenisCarriere** [comment]
Still getting the same error even when I remove all the created files in the photos folder.

**Comment by james2432** [comment]
Added more logging when obtaining sequence id, could you run it again?

**Comment by DenisCarriere** [comment]
I don't think you pushed the commit, the last commit was 20 hours ago.

**Comment by james2432** [comment]
Minor detail, pushed.

**Comment by DenisCarriere** [comment]
Still the same errors:

```
$ java -jar OSVUploadr-0.1.2.1-ALPHA-jar-with-dependencies.jar 
externalUserId:472018|sequenceId:-1
Sep 02, 2016 10:45:28 AM ca.osmcanada.osvuploadr.JPMain SendFinished
SEVERE: null
java.io.IOException: Server returned HTTP response code: 400 for URL: http://openstreetview.com/1.0/sequence/finished-uploading/
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
    at ca.osmcanada.osvuploadr.JPMain.SendFinished(JPMain.java:156)
    at ca.osmcanada.osvuploadr.JPMain.Process(JPMain.java:429)
    at ca.osmcanada.osvuploadr.JPMain.jButton3ActionPerformed(JPMain.java:642)
    at ca.osmcanada.osvuploadr.JPMain.access$300(JPMain.java:58)
    at ca.osmcanada.osvuploadr.JPMain$6.actionPerformed(JPMain.java:482)
```

**Comment by james2432** [comment]
It's like it's skipping over all the images. Have pushed new version

**Comment by DenisCarriere** [comment]
A lot more debugging happened, however still getting errors:

```
id_file exists:true
User ID obtained from file or OSM:472018;DenisCarriere
Processing folder:/Users/mac/Pictures/2016-08-16 5h00pm
Pictures found:0
Sorting files
End sorting
Checking /Users/mac/Pictures/2016-08-16 5h00pm/sequence_file.txt for sequence_file
Sequence file not found, will need to request new id
Looking for count file
Creating new count file:/Users/mac/Pictures/2016-08-16 5h00pm/count_file.txt
Current count at:0
Processing photos...
Sending finish for sequence:-1
externalUserId:472018|sequenceId:-1
Sep 02, 2016 8:37:05 PM ca.osmcanada.osvuploadr.JPMain SendFinished
SEVERE: null
java.io.IOException: Server returned HTTP response code: 400 for URL: http://openstreetview.com/1.0/sequence/finished-uploading/
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
    at ca.osmcanada.osvuploadr.JPMain.SendFinished(JPMain.java:156)
    at ca.osmcanada.osvuploadr.JPMain.Process(JPMain.java:448)
    at ca.osmcanada.osvuploadr.JPMain.jButton3ActionPerformed(JPMain.java:664)
    at ca.osmcanada.osvuploadr.JPMain.access$300(JPMain.java:58)
    at ca.osmcanada.osvuploadr.JPMain$6.actionPerformed(JPMain.java:501)
```

**Comment by DenisCarriere** [comment]
@james2432 Maybe it has to do with the Windows/Linux file path structures.

My pictures directory looks like this:

```
/Users/mac/Pictures/2016-08-16 5h00pm/
```

**Comment by DenisCarriere** [comment]
OMG... You will laugh at this! @james2432 
The JPG file extension was case sensitive, my Garmin VIRB saves them as uppercased JPG.

I changed one of them and it works... When you are parsing the files, just make sure you test for both or use a Regular Expression using the ignore case flag.

![image](https://cloud.githubusercontent.com/assets/550895/18221616/7969af8e-714e-11e6-89d2-b7001571a03d.png)

**Comment by DenisCarriere** [comment]
Success! Here's the log now.

```
$ java -jar OSVUploadr-0.1.2.1-ALPHA-jar-with-dependencies.jar
id_file exists:true
User ID obtained from file or OSM:472018;DenisCarriere
Processing folder:/Users/mac/Pictures/2016-08-16 5h00pm
Pictures found:163
Sorting files
End sorting
Checking /Users/mac/Pictures/2016-08-16 5h00pm/sequence_file.txt for sequence_file
Sequence file not found, will need to request new id
Looking for count file
Creating new count file:/Users/mac/Pictures/2016-08-16 5h00pm/count_file.txt
Current count at:0
Processing photos...
Processing:/Users/mac/Pictures/2016-08-16 5h00pm/VIRB_0370.jpg
Image Properties:
Lat:45.46225277777778 Long:-75.49254444444445Created:1471464954000
Requesting sequence ID
Getting Sequence ID..
currentCoordinate:45.46225277777778,-75.49254444444445
Sending request:externalUserId=472018&clientToken=2ed202ac08ea9cf8d5f290567037dcc42ed202ac08ea9cf8d5f290567037dcc4&currentCoordinate=45.46225277777778%2C-75.49254444444445&userType=osm&userName=DenisCarriere
Request Sent getting sequence response...
Received request:{"status":{"apiCode":"600","apiMessage":" The request has been processed without incidents ","httpCode":200,"httpMessage":"Success"},"osv":{"sequence":{"id":"17209","userId":"82","clientToken":"2ed202ac08ea9cf8d5f290567037dcc42ed202ac08ea9cf8d5f290567037dcc4","dateAdded":"2016-09-03  (02:52)","currentLat":"45.462253","currentLng":"-75.492544","countryCode":"CA","status":"active","imagesStatus":"NEW","metaDataFilename":null,"obdInfo":null,"platformName":null,"platformVersion":null,"appVersion":null,"track":null,"matchTrack":null,"reviewed":"0","changes":"0","recognitions":"0","address":null,"countActivePhotos":"0"}}}
Obtained Sequence ID: sequence_id
Obtained:17209
Uploading image:/Users/mac/Pictures/2016-08-16 5h00pm/VIRB_0370.jpg
Uploading:/Users/mac/Pictures/2016-08-16 5h00pm/VIRB_0370.jpg
{"status":{"apiCode":"600","apiMessage":" The request has been processed without incidents ","httpCode":200,"httpMessage":"Success"},"osv":{"photo":{"id":"8094619","sequenceId":"17209","dateAdded":"2016-09-03  (02:52)","sequenceIndex":"0","photoName":"17209_9cdac_57ca1edb69fe2.jpg","lat":"45.462253","lng":"-75.492544","gpsAccuracy":null,"headers":"4.294967121E9","autoImgProcessingResult":null,"status":null,"multipleInsert":[]}}}
Uploaded
Processing:/Users/mac/Pictures/2016-08-16 5h00pm/VIRB_0371.jpg
Image Properties:
Lat:45.46171944444445 Long:-75.49287222222222Created:1471465016000
Uploading image:/Users/mac/Pictures/2016-08-16 5h00pm/VIRB_0371.jpg
Uploading:/Users/mac/Pictures/2016-08-16 5h00pm/VIRB_0371.jpg
{"status":{"apiCode":"600","apiMessage":" The request has been processed without incidents ","httpCode":200,"httpMessage":"Success"},"osv":{"photo":{"id":"8094620","sequenceId":"17209","dateAdded":"2016-09-03  (02:53)","sequenceIndex":"1","photoName":"17209_a4759_57ca1eeb3e46f.jpg","lat":"45.461719","lng":"-75.492872","gpsAccuracy":null,"headers":"4.294967121E9","autoImgProcessingResult":null,"status":null,"multipleInsert":[]}}}
Uploaded
Processing:/Users/mac/Pictures/2016-08-16 5h00pm/VIRB_0372.jpg
Image Properties:
Lat:45.46171944444445 Long:-75.49287222222222Created:1471465021000
Uploading image:/Users/mac/Pictures/2016-08-16 5h00pm/VIRB_0372.jpg
Uploading:/Users/mac/Pictures/2016-08-16 5h00pm/VIRB_0372.jpg
```

**Comment by james2432** [comment]
Well now...... I guess I'll convert the extension to lower in compare hahahaahaha I was wondering why it wasnt working....

**Comment by DenisCarriere** [comment]
Yea that one was a weird one... Right now I'm I think I've finished...

Is this the last log before it's done?

```
Sending finish for sequence:17209
externalUserId:472018|sequenceId:17209
```

**Comment by james2432** [comment]
Yup

**Comment by DenisCarriere** [comment]
Ok it works!
http://openstreetview.org/details/17209/52

Is the Datetime produced by your script? or by OSV? Because the data of recording says 3 September (today) when the photos were collected in August.

Here's the EXIF:

```
$ gdalinfo VIRB_0370.jpg 
Driver: JPEG/JPEG JFIF
Files: VIRB_0370.jpg
Size is 4608, 3456
Coordinate System is `'
Metadata:
  EXIF_ApertureValue=(2)
  EXIF_ColorSpace=1
  EXIF_ComponentsConfiguration=0x1 0x2 0x3 00
  EXIF_CompressedBitsPerPixel=(1.73999)
  EXIF_Copyright=Copyright 2013
  EXIF_DateTime=2016:08:17 20:15:54
  EXIF_DateTimeDigitized=2016:08:17 20:15:54
  EXIF_DateTimeOriginal=2016:08:17 20:15:54
  EXIF_Document_Name=VIRB
  EXIF_ExifVersion=0210
  EXIF_ExposureBiasValue=(0)
  EXIF_ExposureIndex=(1)
  EXIF_ExposureMode=0
  EXIF_ExposureProgram=3
  EXIF_ExposureTime=(0.0882798)
  EXIF_FileSource=0x3
  EXIF_Flash=0
  EXIF_FlashpixVersion=0100
  EXIF_FNumber=(2)
  EXIF_GPSAltitude=(111)
  EXIF_GPSAltitudeRef=00
  EXIF_GPSImgDirection=(4.29497e+09)
  EXIF_GPSImgDirectionRef=T
  EXIF_GPSLatitude=(45) (27) (44.11)
  EXIF_GPSLatitudeRef=N
  EXIF_GPSLongitude=(75) (29) (33.16)
  EXIF_GPSLongitudeRef=W
  EXIF_GPSSpeed=(20)
  EXIF_GPSSpeedRef=K
  EXIF_ImageDescription=VIRB Picture
  EXIF_Interoperability_Index=R98
  EXIF_Interoperability_Version=0x30 0x31 0x30 0x30
  EXIF_ISOSpeedRatings=0
  EXIF_LightSource=0
  EXIF_Make=Garmin
  EXIF_MakerNote=
  EXIF_MaxApertureValue=(3.7)
  EXIF_MeteringMode=5
  EXIF_Model=VIRB
  EXIF_Orientation=1
  EXIF_PixelXDimension=4608
  EXIF_PixelYDimension=3456
  EXIF_RelatedSoundFile=RelatedSound
  EXIF_ResolutionUnit=2
  EXIF_SceneType=0x1
  EXIF_SensingMethod=2
  EXIF_ShutterSpeedValue=(3.5)
  EXIF_Software=VIRB
  EXIF_WhiteBalance=0
  EXIF_XResolution=(96)
  EXIF_YCbCrPositioning=2
  EXIF_YResolution=(96)
Image Structure Metadata:
  COMPRESSION=JPEG
  INTERLEAVE=PIXEL
  SOURCE_COLOR_SPACE=YCbCr
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0, 3456.0)
Upper Right ( 4608.0,    0.0)
Lower Right ( 4608.0, 3456.0)
Center      ( 2304.0, 1728.0)
Band 1 Block=4608x1 Type=Byte, ColorInterp=Red
  Overviews: 2304x1728, 1152x864, 576x432, 160x120
  Image Structure Metadata:
    COMPRESSION=JPEG
Band 2 Block=4608x1 Type=Byte, ColorInterp=Green
  Overviews: 2304x1728, 1152x864, 576x432, 160x120
  Image Structure Metadata:
    COMPRESSION=JPEG
Band 3 Block=4608x1 Type=Byte, ColorInterp=Blue
  Overviews: 2304x1728, 1152x864, 576x432, 160x120
  Image Structure Metadata:
    COMPRESSION=JPEG
```

**Comment by DenisCarriere** [comment]
And also the Platform says **Unknown** when the EXIF says `EXIF_Model=VIRB`

**Comment by james2432** [comment]
Thats osv they base on upload vs EXIF_DateTimeOriginal=2016:08:17 20:15:54 which I use to put them in order if you convert 1471465016000 from unix time in logs youll see its the time created

**Comment by DenisCarriere** [comment]
Oh ok, well I you're now Mac/Linux compatible 👍  Have the honour to close this issue.

I'll open a new issue if I find something else. For now works like a charm!
