### ISSUE TITLE
failure to get sequence id and fails to upload, fails to finalize

### ISSUE THREAD

**Issue by mprins** [osmottawa/OSVUploadr#13]
after authentication and removing duplicates I tried uploading some pictures; the application fails to ge a sequence id ( the sequence_file.txt contains -1) the app then tries to continue uploading which also fails

log
```
Processing folder:/mnt/tera1/mapillary/SD-kaart/Android/data/app.mapillary/files/mapillary/__uploaded_web/2017_04_26_11_16_19_768
Pictures found:114
Sorting files
End sorting
Checking /mnt/tera1/mapillary/SD-kaart/Android/data/app.mapillary/files/mapillary/__uploaded_web/2017_04_26_11_16_19_768/sequence_file.txt for sequence_file
Sequence file not found, will need to request new id
Looking for count file
Creating new count file:/mnt/tera1/mapillary/SD-kaart/Android/data/app.mapillary/files/mapillary/__uploaded_web/2017_04_26_11_16_19_768/count_file.txt
Current count at:0
Processing photos...
Processing:/mnt/tera1/mapillary/SD-kaart/Android/data/app.mapillary/files/mapillary/__uploaded_web/2017_04_26_11_16_19_768/2017_04_26_11_18_19_182.jpg
Image Properties:
Lat:50.86401888888889 Long:5.719703055555556Created:0
Requesting sequence ID
Getting Sequence ID..
currentCoordinate:50.86401888888889,5.71970305555556
Sending request:access_token=*************************&uploadSource=OSVUploadr&currentCoordinate=50.86401888888889%2C5.71970305555556
Request Sent getting sequence response...
java.io.IOException: Server returned HTTP response code: 400 for URL: http://openstreetview.com/1.0/sequence/
May 02, 2017 10:52:03 AM ca.osmcanada.osvuploadr.JPMain getSequence
SEVERE: null
java.io.IOException: Server returned HTTP response code: 400 for URL: http://openstreetview.com/1.0/sequence/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at ca.osmcanada.osvuploadr.JPMain.getSequence(JPMain.java:492)
	at ca.osmcanada.osvuploadr.JPMain.Process(JPMain.java:718)
	at ca.osmcanada.osvuploadr.JPMain.jbUploadActionPerformed(JPMain.java:1006)
	at ca.osmcanada.osvuploadr.JPMain.access$300(JPMain.java:70)
	at ca.osmcanada.osvuploadr.JPMain$6.actionPerformed(JPMain.java:793)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Obtained:-1
Uploading image:/mnt/tera1/mapillary/SD-kaart/Android/data/app.mapillary/files/mapillary/__uploaded_web/2017_04_26_11_16_19_768/2017_04_26_11_18_19_182.jpg
Uploading:/mnt/tera1/mapillary/SD-kaart/Android/data/app.mapillary/files/mapillary/__uploaded_web/2017_04_26_11_16_19_768/2017_04_26_11_18_19_182.jpg
May 02, 2017 10:52:04 AM ca.osmcanada.osvuploadr.JPMain Upload_Image
SEVERE: null
java.io.IOException: Server returned HTTP response code: 400 for URL: http://openstreetview.com/1.0/photo/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at ca.osmcanada.osvuploadr.JPMain.Upload_Image(JPMain.java:586)
	at ca.osmcanada.osvuploadr.JPMain.Process(JPMain.java:727)
	at ca.osmcanada.osvuploadr.JPMain.jbUploadActionPerformed(JPMain.java:1006)
	at ca.osmcanada.osvuploadr.JPMain.access$300(JPMain.java:70)
	at ca.osmcanada.osvuploadr.JPMain$6.actionPerformed(JPMain.java:793)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Uploaded


............

Sending finish for sequence:-1
accessToken:*************************|sequenceId:-1
May 02, 2017 10:52:38 AM ca.osmcanada.osvuploadr.JPMain SendFinished
SEVERE: null
java.io.IOException: Server returned HTTP response code: 400 for URL: http://openstreetview.com/1.0/sequence/finished-uploading/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at ca.osmcanada.osvuploadr.JPMain.SendFinished(JPMain.java:443)
	at ca.osmcanada.osvuploadr.JPMain.Process(JPMain.java:740)
	at ca.osmcanada.osvuploadr.JPMain.jbUploadActionPerformed(JPMain.java:1006)
	at ca.osmcanada.osvuploadr.JPMain.access$300(JPMain.java:70)
	at ca.osmcanada.osvuploadr.JPMain$6.actionPerformed(JPMain.java:793)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)




```

**Comment by james2432** [comment]
Sending finish for sequence:-1
Probably means your first photo doesn't have either a gps coordinate or compass, as the sequence ID is obtained via the first(ordered by captured datetime) and if OpenStreetCam doesn't have gps coordinates it fails and returns -1

**Comment by mprins** [comment]
the request url for the sequence includes a valid coord pair as show in the log above

**Comment by james2432** [comment]
java.io.IOException: Server returned HTTP response code: 400 for URL: http://openstreetview.com/1.0/sequence/

Says it failed, do you have the sample image?

**Comment by mprins** [comment]
A handful of images is available for download at: https://we.tl/M5hmilH9bP

**Comment by james2432** [comment]
Your exif data doesn't seem to include the compass direction(heading).
![image](https://cloud.githubusercontent.com/assets/498547/25622560/c787efb8-2f22-11e7-85ef-1bd16fc44bd7.png)
I've been working on applying compass angles in batch based on bearing in a new version and is working, but the bulk of my next version isn't done yet (threaded uploads)

Missing compass angle will 100% fail on OSC side.
I'll compile a version with the applying of the compass angle in batch

**Comment by james2432** [comment]
https://github.com/osmottawa/OSVUploadr/releases/tag/v0.2.99
You'll be able to set the bearing via batch:
The degrees are an offset from straight ahead: 
0 = straight
90 = to the right
180 = behind
270 = to the left

**Comment by mprins** [comment]
I'll give that a shot!
It seems the python scripts have some issues as well (eg. allowing upload without bearing in the files, openstreetcam/upload-scripts#22).

FWIW mapillary uses 0 deg (north) as the default heading (when no bearing is present)

**Comment by mprins** [comment]
that version seems to have some an issue with not being able to read the Date/Time:

```
mark@b3p-markprins:~/workspace/OSVUploadr$ java -jar OSVUploadr.jar 
Language:en Country:US
Pictures found:114
Sorting files
Exception in thread "Thread-0" java.lang.NullPointerException
	at ca.osmcanada.osvuploadr.Utils.Helper.getFileTime(Helper.java:85)
	at ca.osmcanada.osvuploadr.JPMain$3.compare(JPMain.java:158)
	at ca.osmcanada.osvuploadr.JPMain$3.compare(JPMain.java:155)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.Arrays.sort(Arrays.java:1438)
	at ca.osmcanada.osvuploadr.JPMain.processBearing(JPMain.java:155)
	at ca.osmcanada.osvuploadr.JPMain$1.run(JPMain.java:127)
id_file exists:true
Access Token obtained from file or OSM:******************************
Processing folder:/mnt/tera1/mapillary/SD-kaart/Android/data/app.mapillary/files/mapillary/__uploaded_web/2017_04_26_11_16_19_768
Pictures found:114
Sorting files
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at ca.osmcanada.osvuploadr.Utils.Helper.getFileTime(Helper.java:85)
	at ca.osmcanada.osvuploadr.JPMain$5.compare(JPMain.java:720)
	at ca.osmcanada.osvuploadr.JPMain$5.compare(JPMain.java:717)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.Arrays.sort(Arrays.java:1438)
	at ca.osmcanada.osvuploadr.JPMain.process(JPMain.java:717)
	at ca.osmcanada.osvuploadr.JPMain.jbUploadActionPerformed(JPMain.java:1095)
	at ca.osmcanada.osvuploadr.JPMain.access$300(JPMain.java:72)
	at ca.osmcanada.osvuploadr.JPMain$9.actionPerformed(JPMain.java:887)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
exiftool for 1st image:

```
mark@b3p-markprins:~$ exiftool /mnt/tera1/mapillary/SD-kaart/Android/data/app.mapillary/files/mapillary/__uploaded_web/2017_04_26_11_16_19_768/2017_04_26_11_16_20_709.jpg 
ExifTool Version Number         : 10.40
File Name                       : 2017_04_26_11_16_20_709.jpg
Directory                       : /mnt/tera1/mapillary/SD-kaart/Android/data/app.mapillary/files/mapillary/__uploaded_web/2017_04_26_11_16_19_768
File Size                       : 781 kB
File Modification Date/Time     : 2017:04:26 11:16:20+02:00
File Access Date/Time           : 2017:05:02 17:58:11+02:00
File Inode Change Date/Time     : 2017:05:01 17:10:47+02:00
File Permissions                : rwxr-----
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Exif Byte Order                 : Little-endian (Intel, II)
Exposure Time                   : 1/526
Camera Model Name               : K007
Exposure Program                : Program AE
F Number                        : 2.4
White Balance                   : Auto
Flash                           : No Flash
Sub Sec Time                    : 693
Create Date                     : 2017:04:26 11:16:20
Sub Sec Time Digitized          : 693
Make                            : ASUS
ISO                             : 100
Focal Length                    : 4.4 mm
Light Source                    : Unknown
Orientation                     : Horizontal (normal)
Metering Mode                   : Average
Sub Sec Time Original           : 693
Modify Date                     : 2017:04:26 11:16:20
GPS Latitude Ref                : North
GPS Longitude Ref               : East
Other Image Start               : 486
Other Image Length              : 0
Image Width                     : 2560
Image Height                    : 1920
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Aperture                        : 2.4
GPS Latitude                    : 50 deg 53' 16.55" N
GPS Longitude                   : 5 deg 44' 23.18" E
GPS Position                    : 50 deg 53' 16.55" N, 5 deg 44' 23.18" E
Image Size                      : 2560x1920
Megapixels                      : 4.9
Shutter Speed                   : 1/526
Create Date                     : 2017:04:26 11:16:20.693
Modify Date                     : 2017:04:26 11:16:20.693
Focal Length                    : 4.4 mm
Light Value                     : 11.6

```

**Comment by james2432** [comment]
Probably because you don't have TAG_DATETIME_ORIGINAL defined in your exif
![image](https://cloud.githubusercontent.com/assets/498547/25629387/57741fa2-2f37-11e7-932e-edeb9cd8eb3e.png)
vs 
![image](https://cloud.githubusercontent.com/assets/498547/25629435/7ad08c38-2f37-11e7-8842-2ae08b0669b3.png)
I'll look for Date Time Digitized exif if the datetime_original is not found that way it will avoid compatibility problems

**Comment by james2432** [comment]
https://github.com/osmottawa/OSVUploadr/releases/tag/v0.2.999
Now accepts Date Digitized and as a last resort the file creation time

**Comment by mprins** [comment]
I've fixed up some things in #16 but there are some other issues such as:

- abnormal values for the direction when inspecting the exif after adding the direction
- still unable to get a sequence id

**Comment by james2432** [comment]
https://www.media.mit.edu/pia/Research/deepview/exif.html
I've been trying to debug your images and Exif SubIFD doesnt seem to contain anything in there:
![image](https://cloud.githubusercontent.com/assets/498547/25756042/4312cf64-3193-11e7-8d95-7866a6807ada.png)
exif:JPEGInterchangeFormat: 474
exif:JPEGInterchangeFormatLength: 0

and the only date I can get from your photos is located in the ExifIFD0 directory.
I think the image is not following EXIF standards and putting it in ExifIFD0 which shouldnt be the case.
added a catch incase photo producers have invalid exif(non spec)

**Comment by Stalfur** [comment]
I'm having the same failure. I have a Virb Elite and thousands of images and am unable to get a sequence ID for even a single image with these tags:
![image](https://user-images.githubusercontent.com/4370958/28387558-19aa04d2-6cbf-11e7-9940-cfd324c15ec1.png)

Mind you the 5500 meters above sea level is about 5200 too much!

**Comment by james2432** [comment]
Do you have a couple sample image I can work with?

**Comment by Stalfur** [comment]
This is the sequence I was testing on, 60 images, 145MB.
https://dl.dropboxusercontent.com/u/71848174/osmuploadr/osmuploadr.zip

**Comment by james2432** [comment]
I'll look into it tomorrow, might be how exif data has been written

**Comment by james2432** [comment]
Another issue, is if one of your images doesnt have gps info, it will crash the whole sequence getting as osv requires it. I can loop until I find gps info to work with/skip those that dont

**Comment by Stalfur** [comment]
Yeah I uploaded to Mapillary first and there it tagged a couple of images as missing GPS so I had already removed them from the folder.

**Comment by james2432** [comment]
Should be able to upload now. There is a new way that was used to handle tokens. You will need to delete access_token.txt to obtain a proper token
https://github.com/osmottawa/OSVUploadr/releases/tag/v0.2.9995
