### ISSUE TITLE
Can't find bundle for base name resources/Bundle, locale fr_CA

### ISSUE THREAD

**Issue by drkludge** [osmottawa/OSVUploadr#6]
Thank you for correcting the release zip.  There is a missing resource.

```
java -jar OSVUploadr.jar
java.util.MissingResourceException: Can't find bundle for base name resources/Bundle, locale fr_CA
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at ca.osmcanada.osvuploadr.JPMain.SetUILang(JPMain.java:105)
        at ca.osmcanada.osvuploadr.JPMain.<init>(JPMain.java:100)
        at ca.osmcanada.osvuploadr.JFMain$1.run(JFMain.java:98)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by james2432** [comment]
Could you try downloading the new zip and try again? I looked at it and seemed like it didn't include the language bundle. The new one has the bundle included

**Comment by drkludge** [comment]
Thanks that fixed the language bundle problem.
